name: Test Build Pythonify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_build:
    name: Test Build on Windows
    runs-on: windows-latest
    timeout-minutes: 30  # Adjust this value as needed

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller python-dotenv

    - name: Download FFmpeg
      run: |
        Invoke-WebRequest -Uri "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip" -OutFile "ffmpeg.zip"
        Expand-Archive -Path "ffmpeg.zip" -DestinationPath "."
        Move-Item -Path "ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe" -Destination "."

    - name: Create .env file with credentials
      run: |
        echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" > .env
        echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> .env

    - name: Test Build with PyInstaller
      run: |
        pyinstaller pythonify.spec
    
    - name: Verify Build
      run: |
        if [ -f "./dist/pythonify_clean.exe" ]; then
          echo "Build successful"
        else
          echo "Build failed"
          exit 1
        fi
      shell: bash
